[package]
name = "libp2p-playground"
version = "0.1.0"
authors = ["Elena Frank <elena.frank@cgi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.2"
futures = "0.3.1"
libp2p = "0.28.1"
